In [76]:
import pandas as pd

In [95]:
current_data = pd.read_csv("cleaned_data_extended.csv", sep=',')
current_data.head()

,Year,Country,Plastic_waste_generated,Plastic_waste_treated,Disposal - Total,Disposal - landfill and other,Disposal - incineration,Recovery - Total,Recovery - energy recovery,Recovery - recycling,Recovery - backfilling
0,2010,Belgium,716165,169210,15002.0,10515.0,4487.0,154208,10259.0,143949,0.0
1,2010,Bulgaria,59950,39690,3722.0,3682.0,40.0,35968,585.0,35383,0.0
2,2010,Czechia,253923,217867,50467.0,50349.0,118.0,167400,44676.0,78375,44349.0
3,2010,Denmark,78548,72125,2377.0,2377.0,0.0,69748,1275.0,68473,0.0
4,2010,Germany,2288466,1828623,54637.0,9641.0,44996.0,1773986,304122.0,1469864,0.0

In [102]:
population = pd.read_csv("PopulationEurope.csv", sep=';')
population = pd.melt(population, id_vars=['Country'])
population['value'] = population['value'].astype('str').str.replace(r".", r"", regex=False)
population = population.rename(columns={'variable': 'Year', 'value': 'Population'})
population['Population'] = population['Population'].astype(str).astype(int)
population['Year'] = population['Year'].astype(str).astype(int)
population.head()

    Country  Year  Population
0   Belgium  2010    11000638
1  Bulgaria  2010     7369431
2   Czechia  2010    10486731
3   Denmark  2010     5560628
4   Germany  2010    80222065

In [103]:
merged_data_population =  current_data.merge(population,on=["Country", "Year"])

In [104]:
merged_data_population["Plastic_waste_generated_per_person"] = (merged_data_population["Plastic_waste_generated"] / merged_data_population["Population"]) *1000

In [124]:
merged_data_population.head()

,Year,Country,Plastic_waste_generated,Plastic_waste_treated,Disposal - Total,Disposal - landfill and other,Disposal - incineration,Recovery - Total,Recovery - energy recovery,Recovery - recycling,Recovery - backfilling,Population,Plastic_waste_generated_per_person
0,2010,Belgium,716165,169210,15002.0,10515.0,4487.0,154208,10259.0,143949,0.0,11000638,65.102133
1,2010,Bulgaria,59950,39690,3722.0,3682.0,40.0,35968,585.0,35383,0.0,7369431,8.134956
2,2010,Czechia,253923,217867,50467.0,50349.0,118.0,167400,44676.0,78375,44349.0,10486731,24.213742
3,2010,Denmark,78548,72125,2377.0,2377.0,0.0,69748,1275.0,68473,0.0,5560628,14.125743
4,2010,Germany,2288466,1828623,54637.0,9641.0,44996.0,1773986,304122.0,1469864,0.0,80222065,28.526640

In [130]:
from google.colab import files
merged_data_population.to_csv('merged_data_population.csv')
files.download('merged_data_population.csv')